version: '3'

tasks:
    default:
        desc: Show available tasks
        cmds:
            - task --list
        silent: true

    install:
        desc: Install dependencies
        cmds:
            - bun install

    dev:
        desc: Run development server
        cmds:
            - bun run dev

    build:
        desc: Build for production
        cmds:
            - bun run build

    lint:
        desc: Run ESLint
        cmds:
            - bun run lint

    format:
        desc: Format code with Prettier
        cmds:
            - bun run format

    format-check:
        desc: Check if code is formatted
        cmds:
            - bun run format:check

    test:
        desc: Run tests
        cmds:
            - bun run test:run

    check:
        desc: Run all checks (format-check, lint, test, build)
        cmds:
            - task: format-check
            - task: lint
            - task: test
            - task: build

    clean:
        desc: Clean generated files
        cmds:
            - rm -rf node_modules dist .vite
            - find . -type f -name "*.log" -delete

    preview:
        desc: Preview production build
        cmds:
            - bun run preview
