version: '3'

tasks:
    default:
        desc: Show available tasks
        cmds:
            - task --list
        silent: true

    install:
        desc: Install dependencies
        cmds:
            - bun install

    dev:
        desc: Run development server
        cmds:
            - bun run dev

    build:
        desc: Build for production
        cmds:
            - bun run build

    lint:
        desc: Run ESLint
        cmds:
            - bun run lint

    format:
        desc: Format code with Prettier
        cmds:
            - bun run format

    format-check:
        desc: Check if code is formatted
        cmds:
            - bun run format:check

    test:
        desc: Run unit tests
        cmds:
            - bun run test:run

    test:watch:
        desc: Run unit tests in watch mode
        cmds:
            - bun run test

    test:coverage:
        desc: Run unit tests with coverage report
        cmds:
            - bun run test:coverage

    test:ui:
        desc: Run tests with Vitest UI
        cmds:
            - bun run test:ui

    test:e2e:
        desc: Run E2E tests with Playwright
        cmds:
            - npx playwright test

    test:e2e:ui:
        desc: Run E2E tests with Playwright UI mode
        cmds:
            - npx playwright test --ui

    test:e2e:headed:
        desc: Run E2E tests in headed mode (see browser)
        cmds:
            - npx playwright test --headed

    storybook:
        desc: Run Storybook development server
        cmds:
            - bun run storybook

    storybook:build:
        desc: Build Storybook for production
        cmds:
            - bun run build-storybook

    check:
        desc: Run all checks (format-check, lint, test, build)
        cmds:
            - task: format-check
            - task: lint
            - task: test
            - task: build

    clean:
        desc: Clean generated files
        cmds:
            - rm -rf node_modules dist .vite coverage storybook-static playwright-report test-results
            - find . -type f -name "*.log" -delete

    preview:
        desc: Preview production build
        cmds:
            - bun run preview
