version: '3'

tasks:
  default:
    desc: Show available tasks
    cmds:
      - task --list
    silent: true

  up:
    desc: Start all services
    cmds:
      - docker compose up -d

  down:
    desc: Stop all services
    cmds:
      - docker compose down --volumes --remove-orphans

  dev:
    desc: Start development environment
    cmds:
      - docker compose --profile dev up

  prod:
    desc: Start production environment
    cmds:
      - docker compose --profile prod up --build

  logs:
    desc: Show service logs
    cmds:
      - docker compose logs -f

  ps:
    desc: Show service status
    cmds:
      - docker compose ps

  clean:
    desc: Remove containers and volumes
    cmds:
      - docker compose down -v
