version: '3'

tasks:
  default:
    desc: Show available tasks
    cmds:
      - task --list
    silent: true

  # Docker services
  up:
    desc: Start all services (postgres, qdrant, ollama, server, client)
    cmds:
      - docker compose up -d

  down:
    desc: Stop all services
    cmds:
      - docker compose down

  logs:
    desc: Show logs from all services
    cmds:
      - docker compose logs -f

  ps:
    desc: Show status of all services
    cmds:
      - docker compose ps

  # Server tasks
  server:install:
    desc: Install server dependencies
    dir: packages/server
    cmds:
      - poetry install --no-root

  server:run:
    desc: Run Flask API server
    dir: packages/server
    cmds:
      - poetry run python src/api.py

  server:test:
    desc: Run server tests with coverage
    dir: packages/server
    cmds:
      - poetry run pytest tests/ -v --cov=src --cov-report=term-missing

  server:format:
    desc: Format server code
    dir: packages/server
    cmds:
      - poetry run black src tests
      - poetry run isort src tests

  server:lint:
    desc: Lint server code
    dir: packages/server
    cmds:
      - poetry run ruff check src tests

  server:type-check:
    desc: Run mypy type checker
    dir: packages/server
    cmds:
      - poetry run mypy src tests

  server:check:
    desc: Run all server checks (format, lint, type-check, test)
    dir: packages/server
    cmds:
      - task: server:format
      - task: server:lint
      - task: server:type-check
      - task: server:test

  # Client tasks
  client:dev:
    desc: Run client in development mode
    dir: packages/client
    cmds:
      - bun run dev

  client:install:
    desc: Install client dependencies
    dir: packages/client
    cmds:
      - bun install

  client:build:
    desc: Build client for production
    dir: packages/client
    cmds:
      - bun run build

  client:test:
    desc: Run client tests
    dir: packages/client
    cmds:
      - bun run test:run

  client:lint:
    desc: Lint client code
    dir: packages/client
    cmds:
      - bun run lint

  client:type-check:
    desc: Run TypeScript type checking
    dir: packages/client
    cmds:
      - bun run build

  client:check:
    desc: Run all client checks (format-check, lint, type-check, test, build)
    dir: packages/client
    cmds:
      - task: client:format-check
      - task: client:lint
      - task: client:type-check
      - task: client:test
      - task: client:build

  client:format:
    desc: Format client code
    dir: packages/client
    cmds:
      - bun run format

  client:format-check:
    desc: Check if client code is formatted
    dir: packages/client
    cmds:
      - bun run format:check

  # Development workflow
  dev:
    desc: Start infrastructure services (postgres, qdrant, ollama)
    cmds:
      - docker compose up -d postgres qdrant ollama ollama-setup

  install:
    desc: Install all dependencies
    cmds:
      - task: server:install
      - task: client:install

  format:
    desc: Format all code
    cmds:
      - task: server:format
      - task: client:format

  test:
    desc: Run all tests
    cmds:
      - task: server:test
      - task: client:test

  check:
    desc: Run all checks (format, lint, type-check, test)
    cmds:
      - task: server:check
      - task: client:check

  clean:
    desc: Remove all containers and volumes
    cmds:
      - docker compose down -v

  clean:all:
    desc: Clean everything (containers, volumes, and generated files)
    cmds:
      - task: clean
      - task: server:clean
      - task: client:clean
