version: '3'

tasks:
  default:
    desc: Show available tasks
    cmds:
      - task --list
    silent: true

  # ==================== Infrastructure ====================
  up:
    desc: Start infrastructure services (PostgreSQL, Ollama, Qdrant, Neo4j)
    cmds:
      - docker compose up -d

  down:
    desc: Stop all running containers (preserves data in volumes)
    cmds:
      - docker compose down --remove-orphans
      - docker network prune -f

  restart:
    desc: Restart all running containers (preserves data)
    cmds:
      - docker compose restart

  logs:
    desc: Show service logs (use -f to follow)
    cmds:
      - docker compose logs -f

  ps:
    desc: Show service status
    cmds:
      - docker compose ps -a

  health-check:
    desc: Check if all backing services are healthy
    cmds:
      - |
        echo "Checking health of backing services..."

        # Check if services are running
        SERVICES="postgres ollama qdrant neo4j minio redis"
        ALL_HEALTHY=true

        for service in $SERVICES; do
          echo -n "Checking $service... "

          # Get container health status
          HEALTH=$(docker compose ps $service --format json | jq -r '.Health // "unknown"')
          STATE=$(docker compose ps $service --format json | jq -r '.State // "unknown"')

          if [ "$STATE" != "running" ]; then
            echo "[FAIL] NOT RUNNING (state: $STATE)"
            ALL_HEALTHY=false
          elif [ "$HEALTH" = "healthy" ] || [ "$HEALTH" = "unknown" ]; then
            echo "[OK] healthy"
          else
            echo "[FAIL] unhealthy (status: $HEALTH)"
            ALL_HEALTHY=false
          fi
        done

        if [ "$ALL_HEALTHY" = false ]; then
          echo ""
          echo "[FAIL] Some services are not healthy. Run 'task up' to start services."
          echo "       Then wait for all services to become healthy before running e2e tests."
          exit 1
        else
          echo ""
          echo "[OK] All backing services are healthy and ready!"
        fi

  clean-docker:
    desc: DESTRUCTIVE - Remove all containers, volumes, and data
    prompt: This will delete all data including databases. Continue?
    cmds:
      - docker compose down -v --remove-orphans
      - docker network prune -f
      - echo "All containers and volumes removed"

  reset:
    desc: DESTRUCTIVE - Reset everything (remove all data, restart services, run migrations)
    prompt: This will delete all data, restart services, and run migrations. Continue?
    cmds:
      - docker compose down -v --remove-orphans
      - docker network prune -f
      - echo "All containers and volumes removed"
      - docker compose up -d
      - echo "Waiting for services to be healthy..."
      - sleep 5
      - cd migrations && ./migrate.sh up

  # ==================== Python Development ====================
  install:
    desc: Install Python dependencies using Poetry
    cmds:
      - poetry install

  setup:
    desc: Install dependencies and download required models
    cmds:
      - poetry install
      - poetry run python -m spacy download en_core_web_sm
      - echo "Setup complete! SpaCy model en_core_web_sm installed."

  lock:
    desc: Lock Python dependencies
    cmds:
      - poetry lock

  format:
    desc: Format Python code with Black and isort
    cmds:
      - poetry run black src tests
      - poetry run isort src tests

  lint:
    desc: Lint Python code with Ruff
    cmds:
      - poetry run ruff check src tests

  type-check:
    desc: Type-check Python code with mypy
    cmds:
      - poetry run mypy src tests

  compile:
    desc: Check Python syntax compilation for all source files
    cmds:
      - |
        echo "Checking Python syntax compilation..."
        python -m py_compile src/**/*.py
        echo "[OK] All files compile successfully"

  unit-test:
    desc: Run unit tests with pytest
    cmds:
      - poetry run pytest tests/unit -v --cov=src

  integration-test:
    desc: Run integration tests with pytest
    cmds:
      - poetry run pytest tests/integration -v

  e2e-test:
    desc: Run e2e tests with pytest (auto-starts backing services if needed)
    cmds:
      - poetry run pytest tests/e2e -v --cov=src

  test:
    desc: Run all tests with pytest
    cmds:
      - task: unit-test
      - task: integration-test
      - task: e2e-test

  check:
    desc: Run all quality checks (compile, format, lint, type-check, test)
    cmds:
      - task: compile
      - task: format
      - task: lint
      - task: type-check
      - task: test

  # ==================== CLI ====================
  cli:
    desc: Run CLI command (usage - task cli -- workspace list)
    cmds:
      - poetry run python -m src.cli {{.CLI_ARGS}}
    silent: true

  # ==================== Database ====================
  migrate-up:
    desc: Run database migrations
    cmds:
      - cd migrations && ./migrate.sh up

  migrate-down:
    desc: Rollback database migrations
    cmds:
      - cd migrations && ./migrate.sh down

  # ==================== Cleanup ====================
  clean:
    desc: Clean Python cache files and build artifacts
    cmds:
      - find . -type d -name "__pycache__" -exec rm -rf {} + 2>/dev/null || true
      - find . -type d -name ".pytest_cache" -exec rm -rf {} + 2>/dev/null || true
      - find . -type d -name ".mypy_cache" -exec rm -rf {} + 2>/dev/null || true
      - find . -type d -name ".ruff_cache" -exec rm -rf {} + 2>/dev/null || true
      - find . -type d -name "*.egg-info" -exec rm -rf {} + 2>/dev/null || true
      - find . -type d -name ".coverage" -exec rm -rf {} + 2>/dev/null || true
      - find . -type d -name ".coverage.*" -exec rm -rf {} + 2>/dev/null || true
      - find . -type d -name "htmlcov" -exec rm -rf {} + 2>/dev/null || true
      - rm -rf dist/ build/ 2>/dev/null || true
      - echo "Python cache and build artifacts removed"

  clean-all:
    desc: Clean everything (cache + Docker data)
    prompt: This will delete all cache and Docker data. Continue?
    cmds:
      - task: clean
      - task: clean-docker
