version: '3'

tasks:
  default:
    desc: Show available tasks
    cmds:
      - task --list
    silent: true

  # --------------------------------------------------------------------------
  # Start services
  # --------------------------------------------------------------------------
  up:
    desc: Start production (infrastructure + server + client)
    cmds:
      - docker compose -f docker-compose.yml -f docker-compose.prod.yml up -d --profile prod
      - cmd: 'echo "Production services started:"'
        silent: true
      - cmd: 'echo "  - Server (prod): http://localhost:5000"'
        silent: true
      - cmd: 'echo "  - Client (prod): http://localhost:3000"'
        silent: true

  up-dev:
    desc: Start development (infrastructure + server + client)
    cmds:
      - docker compose -f docker-compose.yml -f docker-compose.dev.yml up -d --profile dev
      - cmd: 'echo "Development services started:"'
        silent: true
      - cmd: 'echo "  - Server (dev): http://localhost:5000"'
        silent: true
      - cmd: 'echo "  - Client (dev): http://localhost:3000"'
        silent: true
      - cmd: 'echo "  - MinIO Console: http://localhost:9001"'
        silent: true
      - cmd: 'echo "  - PostgreSQL: localhost:5432"'
        silent: true

  up-elk:
    desc: Start ELK stack services
    cmds:
      - docker compose -f docker-compose.elk.yml up -d
      - cmd: 'echo "ELK stack started:"'
        silent: true
      - cmd: 'echo "  - Elasticsearch: http://localhost:9200"'
        silent: true
      - cmd: 'echo "  - Kibana: http://localhost:5601"'
        silent: true

  up-infra:
    desc: Start infrastructure services only (Postgres, MinIO, Ollama, Qdrant, Redis, RabbitMQ)
    cmds:
      - docker compose -f docker-compose.yml up -d postgres minio ollama qdrant redis rabbitmq
      - cmd: 'echo "Waiting for Ollama to be healthy..."'
        silent: true
      - docker compose -f docker-compose.yml up ollama-setup
      - cmd: 'echo "Infrastructure services started."'
        silent: true
      - cmd: 'echo "  - PostgreSQL: localhost:5432"'
        silent: true
      - cmd: 'echo "  - MinIO: http://localhost:9001 (console)"'
        silent: true
      - cmd: 'echo "  - Ollama: http://localhost:11434"'
        silent: true
      - cmd: 'echo "  - Qdrant: http://localhost:6334 (UI)"'
        silent: true
      - cmd: 'echo "  - Redis: localhost:6379"'
        silent: true
      - cmd: 'echo "  - RabbitMQ: http://localhost:15672 (management)"'
        silent: true

  up-workers-dev:
    desc: Start development workers (requires up-dev or up-infra)
    cmds:
      - docker compose -f docker-compose.yml -f docker-compose.dev.yml up -d --profile workers
      - cmd: 'echo "Development worker processes started:"'
        silent: true
      - cmd: 'echo "  - Ingestion worker (document parsing)"'
        silent: true
      - cmd: 'echo "  - Embeddings worker (vector generation)"'
        silent: true
      - cmd: 'echo "  - Graph worker (entity extraction)"'
        silent: true
      - cmd: 'echo "  - Enrichment worker (external knowledge)"'
        silent: true
      - cmd: 'echo "  - Query worker (context preparation)"'
        silent: true
      - cmd: 'echo "  - Retriever worker (internet data)"'
        silent: true

  up-workers:
    desc: Start production workers (requires up or up-infra)
    cmds:
      - docker compose -f docker-compose.yml -f docker-compose.prod.yml up -d --profile workers
      - cmd: 'echo "Production worker processes started:"'
        silent: true
      - cmd: 'echo "  - Ingestion worker (document parsing)"'
        silent: true
      - cmd: 'echo "  - Embeddings worker (vector generation)"'
        silent: true
      - cmd: 'echo "  - Graph worker (entity extraction)"'
        silent: true
      - cmd: 'echo "  - Enrichment worker (external knowledge)"'
        silent: true
      - cmd: 'echo "  - Query worker (context preparation)"'
        silent: true
      - cmd: 'echo "  - Retriever worker (internet data)"'
        silent: true

  up-full:
    desc: Start everything in development (infrastructure + dev + workers)
    cmds:
      - docker compose -f docker-compose.yml -f docker-compose.dev.yml up -d --profile dev --profile workers
      - cmd: 'echo "Full development stack started:"'
        silent: true
      - cmd: 'echo "  - Server (dev): http://localhost:5000"'
        silent: true
      - cmd: 'echo "  - Client (dev): http://localhost:3000"'
        silent: true
      - cmd: 'echo "  - All 6 workers running"'
        silent: true

  down:
    desc: Stop all services
    cmds:
      - docker compose -f docker-compose.yml -f docker-compose.prod.yml -f docker-compose.dev.yml -f docker-compose.elk.yml down

  # --------------------------------------------------------------------------
  # Restart services
  # --------------------------------------------------------------------------
  restart:
    desc: Restart production services
    cmds:
      - docker compose -f docker-compose.yml -f docker-compose.prod.yml restart

  restart-dev:
    desc: Restart development services
    cmds:
      - docker compose -f docker-compose.yml -f docker-compose.dev.yml restart

  # --------------------------------------------------------------------------
  # Show status
  # --------------------------------------------------------------------------
  ps:
    desc: Show status of all services
    cmds:
      - docker compose -f docker-compose.yml -f docker-compose.prod.yml -f docker-compose.dev.yml -f docker-compose.elk.yml ps

  # --------------------------------------------------------------------------
  # Build images
  # --------------------------------------------------------------------------
  build:
    desc: Build all production images
    cmds:
      - docker compose -f docker-compose.yml -f docker-compose.prod.yml build

  build-dev:
    desc: Build all development images
    cmds:
      - docker compose -f docker-compose.yml -f docker-compose.dev.yml build

  build-server:
    desc: Build server production image
    cmds:
      - docker compose -f docker-compose.yml -f docker-compose.prod.yml build server-prod

  build-server-dev:
    desc: Build server development image
    cmds:
      - docker compose -f docker-compose.yml -f docker-compose.dev.yml build server-dev

  build-client:
    desc: Build client production image
    cmds:
      - docker compose -f docker-compose.yml -f docker-compose.prod.yml build client-prod

  build-client-dev:
    desc: Build client development image
    cmds:
      - docker compose -f docker-compose.yml -f docker-compose.dev.yml build client-dev

  clean:
    desc: Remove all containers, images, and volumes
    cmds:
      - docker compose -f docker-compose.yml -f docker-compose.prod.yml -f docker-compose.dev.yml -f docker-compose.elk.yml down -v --rmi all
      - task: server:clean
      - task: client:clean

  # --------------------------------------------------------------------------
  # Logs
  # --------------------------------------------------------------------------
  logs:
    desc: Show logs from all services
    cmds:
      - docker compose -f docker-compose.yml -f docker-compose.prod.yml -f docker-compose.dev.yml -f docker-compose.elk.yml logs -f

  logs-server:
    desc: Show server logs (production)
    cmds:
      - docker compose -f docker-compose.yml -f docker-compose.prod.yml logs -f server-prod

  logs-server-dev:
    desc: Show server logs (development)
    cmds:
      - docker compose -f docker-compose.yml -f docker-compose.dev.yml logs -f server-dev

  logs-client:
    desc: Show client logs (production)
    cmds:
      - docker compose -f docker-compose.yml -f docker-compose.prod.yml logs -f client-prod

  logs-client-dev:
    desc: Show client logs (development)
    cmds:
      - docker compose -f docker-compose.yml -f docker-compose.dev.yml logs -f client-dev

  logs-elk:
    desc: Show ELK logs
    cmds:
      - docker compose -f docker-compose.elk.yml logs -f

  logs-ollama:
    desc: Show Ollama logs
    cmds:
      - docker compose -f docker-compose.yml logs -f ollama

  logs-postgres:
    desc: Show Postgres logs
    cmds:
      - docker compose -f docker-compose.yml logs -f postgres

  logs-minio:
    desc: Show MinIO logs
    cmds:
      - docker compose -f docker-compose.yml logs -f minio

  logs-qdrant:
    desc: Show Qdrant logs
    cmds:
      - docker compose -f docker-compose.yml logs -f qdrant

  logs-redis:
    desc: Show Redis logs
    cmds:
      - docker compose -f docker-compose.yml logs -f redis

  logs-rabbitmq:
    desc: Show RabbitMQ logs
    cmds:
      - docker compose -f docker-compose.yml logs -f rabbitmq

  logs-workers-dev:
    desc: Show all development worker logs
    cmds:
      - docker compose -f docker-compose.yml -f docker-compose.dev.yml logs -f worker-ingestion-dev worker-embeddings-dev worker-graph-dev worker-enrichment-dev worker-query-dev worker-retriever-dev

  logs-workers:
    desc: Show all production worker logs
    cmds:
      - docker compose -f docker-compose.yml -f docker-compose.prod.yml logs -f worker-ingestion-prod worker-embeddings-prod worker-graph-prod worker-enrichment-prod worker-query-prod worker-retriever-prod

  # --------------------------------------------------------------------------
  # Dev shortcuts
  # --------------------------------------------------------------------------
  dev-server:
    desc: Run server in development mode
    cmds:
      - task: server:server

  dev-client:
    desc: Run client in development mode
    cmds:
      - task: client:dev

  # --------------------------------------------------------------------------
  # Subdirectory tasks
  # --------------------------------------------------------------------------
  shared:*:
    desc: Run shared tasks (use task shared:<task-name>)
    dir: packages/shared/python
    cmds:
      - task {{index .MATCH 0}}

  server:*:
    desc: Run server tasks (use task server:<task-name>)
    dir: packages/server
    cmds:
      - task {{index .MATCH 0}}

  client:*:
    desc: Run client tasks (use task client:<task-name>)
    dir: packages/client
    cmds:
      - task {{index .MATCH 0}}

  check:
    desc: Run all checks for shared, server, and client
    cmds:
      - cmd: echo "Running shared checks..."
        silent: true
      - task: shared:check
      - cmd: echo ""
        silent: true
      - cmd: echo "Running server checks..."
        silent: true
      - task: server:check
      - cmd: echo ""
        silent: true
      - cmd: echo "Running client checks..."
        silent: true
      - task: client:check
      - cmd: echo ""
        silent: true
      - cmd: echo "All checks passed!"
        silent: true

  shared:rebuild:
    desc: Rebuild shared package and reinstall in server
    cmds:
      - cmd: echo "Building shared package..."
        silent: true
      - task: shared:build
      - cmd: echo "Reinstalling shared package in server..."
        silent: true
      - cd packages/server && poetry remove insighthub-shared || true
      - cd packages/server && poetry add ../shared/python/dist/insighthub_shared-*.whl

  # --------------------------------------------------------------------------
  # Security tasks (root level)
  # --------------------------------------------------------------------------
  audit:
    desc: Run dependency audits for client and server
    cmds:
      - cmd: echo "Running server audit..."
        silent: true
      - task: server:audit
      - cmd: echo ""
        silent: true
      - cmd: echo "Running client audit..."
        silent: true
      - task: client:audit
      - cmd: echo ""
        silent: true
      - cmd: echo "Audit complete!"
        silent: true

  scan:
    desc: Run code scans for client and server
    cmds:
      - cmd: echo "Running server scan..."
        silent: true
      - task: server:scan
      - cmd: echo ""
        silent: true
      - cmd: echo "Running client scan..."
        silent: true
      - task: client:scan
      - cmd: echo ""
        silent: true
      - cmd: echo "Scan complete!"
        silent: true

  security:
    desc: Run full security checks (audit + scan + Docker image scans)
    cmds:
      - cmd: echo "Running audits..."
        silent: true
      - task: audit
      - cmd: echo "Running code scans..."
        silent: true
      - task: scan
      - cmd: echo "Building Docker images before scanning..."
        silent: true
      - docker compose -f docker-compose.yml -f docker-compose.prod.yml -f docker-compose.dev.yml build client-prod client-dev server-prod server-dev
      - cmd: echo "Scanning Docker images..."
        silent: true
      - cmd: |
          IMAGES=("client-prod" "client-dev" "server-prod" "server-dev")
          for IMAGE in "${IMAGES[@]}"; do
            if docker image inspect insighthub-$IMAGE > /dev/null 2>&1; then
              echo "Scanning image: insighthub-$IMAGE"
              # Scan with Trivy and output JSON for CI/CD
              trivy image insighthub-$IMAGE --ignore-unfixed --format json --output trivy-$IMAGE.json
            else
              echo "Image insighthub-$IMAGE does not exist, skipping..."
            fi
          done
      - cmd: echo "Full security check complete!"
        silent: true
