version: '3'

tasks:
  default:
    desc: Show available tasks
    cmds:
      - task --list
    silent: true

  # ==================== Infrastructure ====================
  up:
    desc: Start infrastructure services (PostgreSQL, Ollama, Qdrant, Neo4j)
    cmds:
      - docker compose up -d

  down:
    desc: Stop all running containers (preserves data in volumes)
    cmds:
      - docker compose down --remove-orphans
      - docker network prune -f

  restart:
    desc: Restart all running containers (preserves data)
    cmds:
      - docker compose restart

  logs:
    desc: Show service logs (use -f to follow)
    cmds:
      - docker compose logs -f

  ps:
    desc: Show service status
    cmds:
      - docker compose ps -a

  clean-docker:
    desc: DESTRUCTIVE - Remove all containers, volumes, and data
    prompt: This will delete all data including databases. Continue?
    cmds:
      - docker compose down -v --remove-orphans
      - docker network prune -f
      - echo "All containers and volumes removed"

  # ==================== Python Development ====================
  install:
    desc: Install Python dependencies using Poetry
    cmds:
      - poetry install

  lock:
    desc: Lock Python dependencies
    cmds:
      - poetry lock

  format:
    desc: Format Python code with Black and isort
    cmds:
      - poetry run black src tests
      - poetry run isort src tests

  lint:
    desc: Lint Python code with Ruff
    cmds:
      - poetry run ruff check src tests

  type-check:
    desc: Type-check Python code with mypy
    cmds:
      - poetry run mypy src tests

  test:
    desc: Run tests with pytest
    cmds:
      - poetry run pytest tests/ -v --cov=src

  check:
    desc: Run all quality checks (format, lint, type-check, test)
    cmds:
      - task: format
      - task: lint
      - task: type-check
      - task: test

  # ==================== CLI ====================
  cli:
    desc: Run CLI command (usage - task cli -- workspace list)
    cmds:
      - poetry run python -m src.cli {{.CLI_ARGS}}
    silent: true

  # ==================== Database ====================
  migrate-up:
    desc: Run database migrations
    cmds:
      - cd migrations && ./migrate.sh up

  migrate-down:
    desc: Rollback database migrations
    cmds:
      - cd migrations && ./migrate.sh down

  migrate-docker:
    desc: Run database migrations in Docker
    cmds:
      - cd migrations && ./migrate.sh up --docker

  # ==================== Cleanup ====================
  clean:
    desc: Clean Python cache files and build artifacts
    cmds:
      - find . -type d -name "__pycache__" -exec rm -rf {} + 2>/dev/null || true
      - find . -type d -name ".pytest_cache" -exec rm -rf {} + 2>/dev/null || true
      - find . -type d -name ".mypy_cache" -exec rm -rf {} + 2>/dev/null || true
      - find . -type d -name ".ruff_cache" -exec rm -rf {} + 2>/dev/null || true
      - find . -type d -name "*.egg-info" -exec rm -rf {} + 2>/dev/null || true
      - find . -type d -name ".coverage" -exec rm -rf {} + 2>/dev/null || true
      - find . -type d -name "htmlcov" -exec rm -rf {} + 2>/dev/null || true
      - rm -rf dist/ build/ 2>/dev/null || true
      - echo "Python cache and build artifacts removed"

  clean-all:
    desc: Clean everything (cache + Docker data)
    prompt: This will delete all cache and Docker data. Continue?
    cmds:
      - task: clean
      - task: clean-docker
