version: '3'

tasks:
  default:
    desc: Show available tasks
    cmds:
      - task --list
    silent: true

  up:
    desc: Start all production services
    cmds:
      - docker compose --profile prod up -d

  up-dev:
    desc: Start all development services (infrastructure + dev containers)
    cmds:
      - docker compose --profile dev up -d
      - cmd: 'echo "Development services started:"'
        silent: true
      - cmd: 'echo "  - Server (dev): http://localhost:5000"'
        silent: true
      - cmd: 'echo "  - Client (dev): http://localhost:3000"'
        silent: true
      - cmd: 'echo "  - MinIO Console: http://localhost:9001"'
        silent: true
      - cmd: 'echo "  - PostgreSQL: localhost:5432"'
        silent: true

  up-infra:
    desc: Start infrastructure services only (Postgres, MinIO, Ollama)
    cmds:
      - docker compose up -d postgres minio ollama
      - cmd: 'echo "Waiting for Ollama to be healthy..."'
        silent: true
      - docker compose up ollama-setup
      - cmd: 'echo ""'
        silent: true
      - cmd: 'echo "Infrastructure services started. Run local dev servers with:"'
        silent: true
      - cmd: 'echo "  - Server: task dev-server (or cd packages/server && task server)"'
        silent: true
      - cmd: 'echo "  - Client: task dev-client (or cd packages/client && task dev)"'
        silent: true

  down:
    desc: Stop all services
    cmds:
      - docker compose --profile prod --profile dev down

  restart:
    desc: Restart all production services
    cmds:
      - docker compose --profile prod restart

  restart-dev:
    desc: Restart all development services
    cmds:
      - docker compose --profile dev restart

  ps:
    desc: Show status of all services
    cmds:
      - docker compose --profile prod --profile dev ps

  build:
    desc: Build all production images
    cmds:
      - docker compose --profile prod build

  build-dev:
    desc: Build all development images
    cmds:
      - docker compose --profile dev build

  build-server:
    desc: Build server production image
    cmds:
      - docker compose build server-prod

  build-server-dev:
    desc: Build server development image
    cmds:
      - docker compose build server-dev

  build-client:
    desc: Build client production image
    cmds:
      - docker compose build client-prod

  build-client-dev:
    desc: Build client development image
    cmds:
      - docker compose build client-dev

  clean:
    desc: Remove all containers, images, and volumes
    cmds:
      - docker compose down -v --rmi all
      - task: server:clean
      - task: client:clean

  check:
    desc: Run all checks for both client and server
    cmds:
      - cmd: echo "Running server checks..."
        silent: true
      - task: server:check
      - cmd: echo ""
        silent: true
      - cmd: echo "Running client checks..."
        silent: true
      - task: client:check
      - cmd: echo ""
        silent: true
      - cmd: echo "All checks passed!"
        silent: true

  logs:
    desc: Show logs from all services
    cmds:
      - docker compose logs -f

  logs-server:
    desc: Show server logs (production)
    cmds:
      - docker compose logs -f server-prod

  logs-server-dev:
    desc: Show server logs (development)
    cmds:
      - docker compose logs -f server-dev

  logs-client:
    desc: Show client logs (production)
    cmds:
      - docker compose logs -f client-prod

  logs-client-dev:
    desc: Show client logs (development)
    cmds:
      - docker compose logs -f client-dev

  logs-ollama:
    desc: Show Ollama logs
    cmds:
      - docker compose logs -f ollama

  logs-postgres:
    desc: Show Postgres logs
    cmds:
      - docker compose logs -f postgres

  logs-minio:
    desc: Show MinIO logs
    cmds:
      - docker compose logs -f minio

  dev-server:
    desc: Run server in development mode
    cmds:
      - task: server:server

  dev-client:
    desc: Run client in development mode
    cmds:
      - task: client:dev

  # Included tasks from subdirectories
  server:*:
    desc: Run server tasks (use task server:<task-name>)
    dir: packages/server
    cmds:
      - task {{index .MATCH 0}}

  client:*:
    desc: Run client tasks (use task client:<task-name>)
    dir: packages/client
    cmds:
      - task {{index .MATCH 0}}
