version: '3'

tasks:
  default:
    desc: Show available tasks
    cmds:
      - task --list
    silent: true

  source:
    desc: Source environment variables from config files
    cmds:
      - bash config/source.sh {{.ENV_FILE | default ".env.local"}}

  migrate:
    desc: Run database migrations
    cmds:
      - python migrations/migrate.py

  migrate:status:
    desc: Show migration status
    cmds:
      - python migrations/migrate.py --status

  migrate:create:
    desc: 'Create new migration (usage: task migrate:create -- NAME)'
    cmds:
      - python migrations/migrate.py --create "{{.MIGRATION_NAME}}"

  config:validate:
    desc: Validate configuration files
    cmds:
      - echo "Validating configuration..."
      - |
        if [ ! -f "config/.env.local" ] && [ ! -f "config/.env" ]; then
          echo "ERROR: No environment file found in config/"
          echo "Available example files:"
          ls -la config/.env.*.example 2>/dev/null || echo "  No example files found"
          echo ""
          echo "Run: cp config/.env.local.example config/.env.local"
          exit 1
        fi
      - echo "Configuration files found"

  infra:check:
    desc: Check infrastructure health
    cmds:
      - task: config:validate
      - echo "Infrastructure check passed"

  audit:
    desc: Audit infrastructure dependencies for vulnerabilities
    cmds:
      - echo "Running Trivy filesystem scan..."
      - trivy fs --scanners vuln --ignore-unfixed .

  scan:
    desc: Scan infrastructure code for security issues
    cmds:
      - echo "Running Bandit code scan..."
      - python -m bandit -r . -c pyproject.toml || echo "Bandit not available, skipping..."