
version: '3'

tasks:
  default:
    desc: Show available tasks
    cmds:
      - task --list
    silent: true

  test:
    desc: Run all tests
    cmds:
      - ENVIRONMENT=testing PYTHONPATH=. poetry run pytest tests/

  format:
    desc: Format code with black and isort
    cmds:
      - poetry run black src tests
      - poetry run isort src tests

  lint:
    desc: Run ruff linter
    cmds:
      - poetry run ruff check src tests

  type-check:
    desc: Run mypy type checker
    cmds:
      - poetry run mypy src tests

  check:
    desc: Run all checks (format, lint, type-check, test)
    cmds:
      - task: format
      - task: lint
      - task: type-check
      - task: test

  audit:
    desc: Audit Python dependencies for vulnerabilities
    cmds:
      - echo "Running pip-audit on current Poetry environment..."
      - poetry run pip-audit
      - echo "Running Trivy dependency scan..."
      - trivy fs --scanners vuln --ignore-unfixed .

  scan:
    desc: Scan Python code for security issues
    cmds:
      - echo "Running Bandit code scan..."
      - poetry run bandit -r src
