INSERT INTO products (id, name, description, price) VALUES
(1, 'Wireless Noise-Cancelling Headphones', 'High-fidelity over-ear headphones with active noise cancellation and long battery life.', 249.99),
(2, 'Ergonomic Office Chair', 'Adjustable office chair with lumbar support, breathable mesh back, and comfortable cushioning.', 179.50),
(3, 'Smart LED Desk Lamp', 'Dimmable LED desk lamp with adjustable color temperatures and USB charging port.', 59.95),
(4, 'Stainless Steel Cookware Set', 'Premium 10-piece stainless steel cookware set designed for durability and even heat distribution.', 329.00),
(5, '4K Ultra HD Projector', 'High-resolution projector with vivid colors, low latency, and versatile connectivity.', 799.00);

INSERT INTO reviews (author, rating, content, createdAt, productId) VALUES
('Sarah Thompson', 5, 'These headphones exceeded my expectations in every way. The noise cancellation is incredibly effective, blocking out chatter at the coffee shop and the hum of the airplane. The sound quality is crisp, with deep bass and balanced mids and highs. I wore them for over five hours straight without discomfort, and the battery lasted me an entire weekend trip. Perfect for both music and podcasts.', NOW(), 1),
('Michael Rodriguez', 4, 'I purchased these headphones for work and travel, and they have been a game-changer. The build quality feels premium, and the ear cups are plush. Noise cancellation is solid, though not absolute. I love that I can connect them to two devices at once, which makes switching between my laptop and phone seamless. The only downside is the case feels a bit bulky.', NOW(), 1),
('Emily Carter', 5, 'The sound profile on these headphones is phenomenal. I can hear details in my favorite tracks that I never noticed before. Calls are clear, and the microphone works surprisingly well in noisy environments. The quick-charge feature is very handy when I forget to plug them in overnight. They have become my daily go-to for commuting and working from home.', NOW(), 1),
('Daniel Foster', 3, 'While the headphones are comfortable and sound good, I found the noise cancellation to be underwhelming compared to other models I have tried. They block out some noise, but lower-frequency sounds still come through. The app that controls them also feels a bit clunky. They are still good headphones, but not perfect for the price point.', NOW(), 1),
('Jessica Lee', 5, 'I am thrilled with these headphones. I use them daily for focus at work, and they drown out the noisy office perfectly. The music playback is immersive, with rich tones and strong bass that makes listening enjoyable. The controls on the earcups are intuitive and responsive. They feel worth every penny I spent.', NOW(), 1),

('Anthony Miller', 5, 'This chair has completely changed how I feel at the end of a long workday. The lumbar support is excellent, and I no longer have lower back pain. The mesh material is breathable, keeping me cool even in summer. Adjustments are easy to make, and I found my perfect sitting position in minutes. It feels sturdy and supportive, with no wobbling or creaking.', NOW(), 2),
('Rebecca Wilson', 4, 'I work from home full-time, and after switching to this chair, my posture has improved noticeably. The seat cushion is firm yet comfortable, and the recline mechanism is smooth. It does take some time to put together, and the instructions weren’t the clearest, but the result is worth it. I would highly recommend it to anyone spending long hours at a desk.', NOW(), 2),
('James Peterson', 5, 'Comfortable, stylish, and supportive. This chair is everything I was hoping for in an ergonomic office chair. I spend over eight hours a day working, and my back and shoulders feel supported. The adjustable arms and seat height allow me to customize it to my exact preference. It looks sleek in my office and feels like it will last a long time.', NOW(), 2),
('Laura Martinez', 3, 'The chair is decent but not outstanding. It does provide good lumbar support, but the armrests feel flimsy, and the cushion is a bit firm for my liking. Assembly was not too difficult, though some screws didn’t line up perfectly. For the price, I expected a little more polish in the finish.', NOW(), 2),
('David Nguyen', 5, 'I have tried several office chairs over the years, and this one is by far the most comfortable. It keeps me upright, promotes good posture, and prevents fatigue during long meetings. The breathable mesh is a huge improvement over my old leather chair. It feels like a serious upgrade and has already made a noticeable difference in my productivity.', NOW(), 2),

('Olivia Harris', 5, 'This lamp is perfect for my study desk. The multiple brightness levels make it great for reading, working on my laptop, or winding down at night. I especially appreciate the adjustable color temperature, which lets me switch from warm light to cool daylight depending on the task. The USB port on the base is super convenient for charging my phone.', NOW(), 3),
('Christopher Adams', 4, 'The design of this lamp is sleek and minimalistic, fitting perfectly with my modern workspace. The touch controls are responsive, and the adjustable neck allows me to direct light exactly where I need it. The only small drawback is that the lamp base feels a bit light, so it can wobble if bumped. Otherwise, it’s a fantastic buy.', NOW(), 3),
('Sophia Turner', 5, 'I bought this lamp for my daughter’s desk, and she loves it. The light is gentle on the eyes, and she uses the warm mode when reading before bed. The brightness adjustment is smooth, and the lamp itself takes up very little space. It has become an essential part of her nightly routine. Excellent quality for the price.', NOW(), 3),
('Matthew Evans', 4, 'This desk lamp offers great flexibility with lighting modes, and I appreciate the energy efficiency. The build quality feels solid, though I wish the base were slightly heavier for more stability. Still, it is a very practical and stylish lamp, and I would definitely recommend it to others looking for a compact lighting solution.', NOW(), 3),
('Grace Collins', 5, 'I am so impressed with this lamp. It provides excellent illumination without glare, making it ideal for long study sessions. The touch dimmer is smooth, and the USB charging port is a lifesaver. I use it every day, and it has held up very well. Highly recommended for students or anyone working from home.', NOW(), 3),

('Ethan Johnson', 5, 'This cookware set is top-notch. The stainless steel feels durable and distributes heat evenly across the pan. I’ve cooked everything from delicate sauces to seared steaks, and the results have been fantastic. The handles stay cool, and cleanup is surprisingly easy for stainless steel. This set has completely upgraded my cooking experience.', NOW(), 4),
('Isabella Davis', 4, 'I am very happy with this cookware set. The pieces are versatile and well-designed, and they look beautiful in my kitchen. The only challenge is that food can stick if you don’t preheat properly, but that’s expected with stainless steel. Once you learn the technique, these pans are wonderful to use. I can see them lasting for years.', NOW(), 4),
('William Scott', 5, 'The quality of this cookware set is undeniable. The weight of the pots and pans is just right, and they heat quickly and evenly. I appreciate that they work perfectly on my induction cooktop. They feel like professional-grade tools, and I actually enjoy cooking more because of them. Worth every cent.', NOW(), 4),
('Natalie Parker', 3, 'The cookware is nice, but I found it takes some getting used to compared to non-stick. Eggs in particular are tricky unless I use plenty of oil or butter. On the positive side, they clean up nicely with some scrubbing, and they feel very sturdy. I do like the set, but it may not be ideal for beginners.', NOW(), 4),
('Ryan Brooks', 5, 'I cannot recommend this cookware set enough. It is beautifully crafted and performs exceptionally well. The heat distribution is excellent, and the lids fit snugly. I’ve been experimenting with new recipes and consistently get amazing results. This set feels like something that will be in my kitchen for decades.', NOW(), 4),

('Hannah Moore', 5, 'This projector has transformed our family movie nights. The 4K picture is incredibly sharp, with vibrant colors and deep contrast. Setting it up was straightforward, and it connected easily to our streaming devices. Even in a room with some ambient light, the picture quality remains excellent. It feels like having a cinema at home.', NOW(), 5),
('Joshua Bennett', 4, 'I use this projector for gaming and movies, and the low latency is a big plus. The resolution is outstanding, and the brightness is sufficient even during the day. The fan is a bit louder than I’d like, but it’s not distracting once the audio is turned up. Overall, I’m very pleased with the purchase.', NOW(), 5),
('Mia Ramirez', 5, 'Absolutely fantastic projector. The clarity and detail in the image are stunning, and watching sports on it is a whole new experience. The colors are rich and lifelike, and I appreciate the multiple input options. It’s been reliable so far, and setup was easy. Definitely one of the best investments for home entertainment I’ve made.', NOW(), 5),
('Alexander White', 4, 'The projector delivers on its promise of 4K resolution, and the image quality is truly impressive. I use it in my home theater setup, and it feels immersive. The only drawback is that it is slightly larger than expected, so it requires some planning for placement. Aside from that, it’s an excellent device.', NOW(), 5),
('Chloe Walker', 5, 'I am blown away by this projector. It produces a crisp, bright picture that makes every movie feel cinematic. The colors are vibrant, and there is very little lag when streaming or gaming. It was easy to mount and configure. It has quickly become the centerpiece of my living room.', NOW(), 5);
