version: '3'

tasks:
  default:
    desc: Show available tasks
    cmds:
      - task --list
    silent: true

  install:
    desc: Install dependencies
    cmds:
      - poetry install --no-root

  test:
    desc: Run tests
    cmds:
      - poetry run pytest tests/

  format:
    desc: Format code
    cmds:
      - poetry run black src tests
      - poetry run isort src tests

  lint:
    desc: Run linter
    cmds:
      - poetry run ruff check src tests

  check:
    desc: Run checks (format, lint, test)
    cmds:
      - task: format
      - task: lint
      - task: test

  server:
    desc: Run server
    cmds:
      - poetry run python src/main.py

  clean:
    desc: Clean generated files
    cmds:
      - rm -rf .pytest_cache .mypy_cache .ruff_cache htmlcov .coverage
