version: "3"

tasks:
  default:
    desc: Show available tasks
    cmds:
      - task --list
    silent: true

  build:
    desc: Build the shared TypeScript package
    cmds:
      - bun run build

  test:
    desc: Run tests for shared package
    cmds:
      - bun test tests/

  lint:
    desc: Run linting for shared package
    cmds:
      - bun run lint

  format:
    desc: Format code for shared package
    cmds:
      - bun run format

  check:
    desc: Run all checks for shared package
    cmds:
      - task: format
      - task: lint
      - task: build
      - task: test

  clean:
    desc: Clean build artifacts
    cmds:
      - rm -rf dist node_modules
