version: '3'

tasks:
  default:
    desc: Show available tasks
    cmds:
      - task --list
    silent: true

  build:
    desc: Build the shared TypeScript package
    cmds:
      - npm run build

  test:
    desc: Run tests for shared package
    cmds:
      - echo "No tests configured for shared package yet"

  lint:
    desc: Run linting for shared package
    cmds:
      - npm run lint

  format:
    desc: Format code for shared package
    cmds:
      - npm run format

  check:
    desc: Run all checks for shared package
    cmds:
      - task: lint
      - task: build

  clean:
    desc: Clean build artifacts
    cmds:
      - rm -rf dist node_modules