# Graph Construction Worker Tasks
# This worker builds Neo4j graphs from extracted entities and relationships

version: '3'

tasks:
  run:
    desc: Run the graph construction worker locally
    cmds:
      - python -m src.main

  test:
    desc: Run worker tests (when implemented)
    cmds:
      - echo "Tests not yet implemented"

  format:
    desc: Format code with black and isort
    cmds:
      - black src/
      - isort src/

  clean:
    desc: Clean up Python cache files
    cmds:
      - find . -type f -name "*.pyc" -delete
      - find . -type d -name "__pycache__" -delete